simulation:
  seed: 123

fiber:
  length: 10.0                  # [m]
  n_core: 1.4682
  rayleigh_coefficient_dB: -82  # [dB/m]

source:
  center_wavelength: 1.550e-6   # [m]
  sweep_range: 4.0e-8           # [m],  40 nm
  sweep_duration: 0.01          # [s], 10 ms
  power: 1.0e-2                 # [W], 10 mW

optics:
  splitting_ratio: 0.5          # 50/50 coupler

detection:
  responsivity: 1.0             # [A/W]
  shot_noise: true
  thermal_nep: 1.0e-11          # [W/sqrt(Hz)]
  dark_current: 1.0e-9          # [A]

adc:
  bits: 16
  sample_rate: 2.0e+8           # [Hz], 200 MS/s
  voltage_range: 2.0            # [V],
  input_impedance: 50           # [ohm]
